name: Latex Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        docker run --rm -t --user="$(id -u):$(id -g)" --net=none -v "$(pwd):/tmp" leplusorg/latex latexmk -synctex=1 -interaction=nonstopmode -pdf /tmp/main.tex

    - name: Archive PDF
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: |
          main.pdf
        if-no-files-found: warn
